personal_project: Paklan-iOS
name: Felipe Lima

repo_names:
  - ATLAS-iOS-Fall-22
  - Paklan-iOS

10-ux-ui-criticism:
  - Lockscreen -> https://youtu.be/X9GyoscXuSA
  - Notion -> https://youtu.be/EoujOMLUFgo

11-models-from-data:
  - https://github.com/felipeflima/ATLAS-iOS-Fall-22/tree/main/Assignments/ModelFromData
  
project-check-in-1: https://github.com/felipeflima/ATLAS-iOS-Fall-22/issues/2
