personal_project: Paklan-iOS
name: Felipe Lima

repo_names:
  - ATLAS-iOS-Fall-22
  - Paklan-iOS

10-ux-ui-criticism:
  - Lockscreen -> https://youtu.be/X9GyoscXuSA
  - Notion -> https://youtu.be/EoujOMLUFgo

11-models-from-data:
